### ISSUE TITLE
US NF 22 - Usability Testing

### ISSUE THREAD

**Issue by QuitoTactico** [QuitoTactico/SoftServe-Academy#17]
- *Description:* Conduct usability tests with at least a representative group of 5 to 10 users to achieve a success rate of at least 95% in completing key tasks.
- *Acceptance Criteria:*
  - Usability testing sessions are conducted.
  - Test results show a 95% success rate in key tasks.
- *Tasks:*
  - Design usability test scenarios.
  - Recruit and conduct tests with participants.
  - Analyze and report results.
- *Effort Estimation:* 13 hours

**Comment by MiguelCock** [comment]
(Sprint 1) We managed to make the test with 5 users but the success rate wasn't satisfied, we will improve the application base on the feed back and run the test again.
