### ISSUE TITLE
US NF 26 - Scalability

### ISSUE THREAD

**Issue by Jonathanbees** [QuitoTactico/SoftServe-Academy#24]
- *Description:* Horizontal scalability to add at least 1,000 additional users per month without performance degradation.
- *Acceptance Criteria:*
  - The system handles increased user load without performance loss.
  - Infrastructure supports scalability without major changes.
- *Tasks:*
  - Implement scalable infrastructure.
  - Conduct load testing to simulate user growth.
  - Optimize system architecture for scalability.
- *Effort Estimation:* 16 hours

**Comment by QuitoTactico** [comment]
The system architecture was successfully optimized for scalability using Docker Swarm. 3 instances (one manager and two workers) were deployed, running a total of 5 Django web containers and one MySQL container. The application was accessible via [http://34.72.154.173](http://34.72.154.173), demonstrating load balancing and high availability. This setup allows for further scaling by adding more nodes and containers as needed, fulfilling the scalability requirements of this issue.

**Comment by QuitoTactico** [comment]
Deployment with 5 django containers and 1 MySQL container distributed along 3 EC2 instances:  
![Image](https://github.com/user-attachments/assets/c4de6451-df30-4d54-b822-0a47d8ffd84d)

Containers distribution:  
![Image](https://github.com/user-attachments/assets/d5964b70-c8cf-4a78-849e-3a2f2ead74d3)
